### ISSUE TITLE
limit requests to AppBrain

### ISSUE THREAD

**Issue by uwemaurer** [seime/openhab-panasoniccomfortcloud#1]
Hi, 

can you rate limit the requests to appbrain.com please? this code tried to do 3M requests in the last 24 hours. I had to enable a captcha to prevent it.

**Comment by seime** [comment]
Thanks for letting me know. There was a bug in the init logic that was fixed a few weeks back, but not sure how many users are still on the old version. 

I can add a header to provide some user-agent info?
